params: [advertiser, campaign]
data:
  cover:
    dataset: all
    dimensions: [advertiser]
    metrics:
      - impressions
      - clicks
      - conversions
      - video_starts
  streaming_performance:
    dataset: all
    dimensions: [advertiser, tactic]
    metrics:
      - impressions
      - vcr
      - completions100
    filters: tactic:any:Streaming
  video_performance:
    dataset: all
    dimensions: [advertiser, tactic]
    metrics:
      - impressions
      - vcr
      - completions100
    filters: tactic:any:Online Video
  display_performance:
    dataset: all
    dimensions: [advertiser, tactic]
    metrics:
      - impressions
      - clicks
      - click_rate
    filters: tactic:any:Display
